### ISSUE TITLE
Retina support?

### ISSUE THREAD

**Issue by chrisspiegl** [gambitph/WP-OTF-Regenerate-Thumbnails#4]
As far as I see, this plugin will automatically return the size the browser requests. Meaning, if the html states `<img width="600" height="300"...>` the regenerate plugin will give that size. But what if the user has a retina display? Will it take this into consideration or not?

**Comment by bfintal** [comment]
Nope, it has nothing to do with html attributes & browser requests. It prior to that, and more geared towards working with WordPress' thumbnail & attachment functions.

For example, normally when you get an image via `wp_get_attachment_image_src` and specify a width & height, the image you'll get won't be that size since WordPress didn't generate a thumbnail with that size. OTF fixes these kinds of scenarios :)

**Comment by chrisspiegl** [comment]
Ok, thanks for clarifying.
